name: VSCODE-DEV-CONTAINERS
on:
  push:
    branches: [for-aisuko]
    tags:
    - 'av*'

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Docker login
      if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master') && success()
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set properties file with release tag
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        echo git-sha:${GITHUB_SHA::8} >> properties.yml
        echo release-tag:${GITHUB_REF/refs\/tags\//} >> properties.yml
    - name: Docker build & tag
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      run: |
        DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.RUFUS }}:${GITHUB_REF/refs\/tags\//} ${{ secrets.RUFUS_PATH }}
        DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.RED_THIRTEEN }}:${GITHUB_REF/refs\/tags\//} ${{ secrets.RED_THIRTEEN_PATH }}
    - name: Docker push
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      run: |
        docker push ${{ secrets.RUFUS }}:${GITHUB_REF/refs\/tags\//}
        docker push ${{ secrets.RED_THIRTEEN }}:${GITHUB_REF/refs\/tags\//}
    - name: Docker Hub Description
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: peter-evans/dockerhub-description@v2.0.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.RUFUS }}
